"""Add Product

Revision ID: 241446175534
Revises: c95f43a0ad56
Create Date: 2025-11-29 23:59:59.732763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241446175534'
down_revision = 'c95f43a0ad56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###