"""Add active column to products

Revision ID: 550058c761ef
Revises: 6ca04cd3c42a
Create Date: 2025-11-30 00:04:13.967698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550058c761ef'
down_revision = '6ca04cd3c42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
