"""Add Users

Revision ID: 807454228f0d
Revises: f5afc5c8b3d0
Create Date: 2025-11-30 01:04:22.151811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807454228f0d'
down_revision = 'f5afc5c8b3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('password_hash', name=op.f('uq_users_password_hash')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
